### ISSUE TITLE
New display mode - 5 tick + remaining time combo

### ISSUE THREAD

**Issue by sol3uk** [func-vehicle/gtamanager#10]
It'd be cool to have 5 tick display as well as the time displayed somewhere (maybe not over the top of the bar) 
I'm able to try and contribute if you like? :)

**Comment by NGDM** [comment]
Might add to this by making it possible to show the time only in minutes. That way we can easily see if a business needs another resupply or it will fill up with current supplies. E.g. Now you see 1+H which could mean 1H59 or 1H01.

I'd like to take the time to thank you for this great tool! It's a huge help in managing multiple business in GTA and has actually saved me money while doing it. More people should know of this.

**Comment by func-vehicle** [comment]
@NGDM I've changed the time remaining bar style to show hours + minutes, or minutes + seconds, or just seconds, depending on the time left.
