### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by SavnoorSamra** [func-vehicle/gtamanager#15]
Any progress on an android app being made? The web page doesn't run in the background when I'm afking

**Comment by func-vehicle** [comment]
I won't be making an Android app (at least not right now), but I am looking into a fix to make it keep track of businesses even if the phone is asleep.

**Comment by func-vehicle** [comment]
Hi again, check out the latest update. I fixed a _really_ silly mistake and it should now keep track properly even if the phone is asleep or the browser is not the active app.

**Comment by func-vehicle** [comment]
You can now install the Business Manager as a PWA, [see here for details](https://github.com/func-vehicle/gtamanager#installing-as-a-pwa).
