### ISSUE TITLE
Weed Business production time seems off

### ISSUE THREAD

**Issue by NGDM** [func-vehicle/gtamanager#21]
I'm noticing that my Weed business produces faster and more than what is calculated by the GTA Manager.
Could you check the timer?

**Comment by func-vehicle** [comment]
I personally don't own the Weed business so I haven't been able to test it myself, but I've been using [this chart](https://cdn.gtaboom.com/wp-content/uploads/2017/05/bikersbusinesses.png) for setting the production times.

I would expect it to be slightly out of sync with the actual value, but if it's actually producing more than what the manager says when finished with supplies, then I guess the information on that chart is out of date. In that case, it would be a big help if you were able to record the time from full supplies to empty and how many units of product that makes (using the computer to read off the exact values), but I understand if you don't want to.

**Comment by func-vehicle** [comment]
Should be fixed in d2859f60aace2c1fb5fa64a2d9a7737045f9eb04 (v1.10.0), reopen this issue if it isn't.
