### ISSUE TITLE
Download data button not working on mobile

### ISSUE THREAD

**Issue by Aahil52** [func-vehicle/gtamanager#25]
The button does nothing when pressed in a mobile browser

**Comment by func-vehicle** [comment]
What browser are you using? I just tested in Chrome and Firefox mobile and it seems to be working.

**Comment by Aahil52** [comment]
I'm using it in a basic ios app I made using UIWebView. I checked in safari, and sure enough, downloading the data there works. Not sure why it's different since safari and UIWebView are essentially the same as far as I know. I still can't use the manager itself in safari because when I start it it constantly shows a pop up saying something like notifications aren't available. That's why I use the app I made.

**Comment by func-vehicle** [comment]
I can imagine why - currently the way that the file gets saved is stupid (it converts it to data: link in the address bar). I've found a better way of doing this with a library, so I'll convert it to that in the next update. It also doesn't work in Edge, so thanks for pointing this out.

As for the Safari issue, I see why it keeps giving that alert message. I'll fix that too.

**Comment by Aahil52** [comment]
Great that you know a fix! A few other minor things on mobile I wanted to point out. The sliders can be a little hit or miss if you want to adjust it by sliding your finger on it, and when the browser is in the background, sometimes it pauses. Other than that, the manager is great and super useful! Way better than spending 3 mil+ to get a master control terminal.

**Comment by func-vehicle** [comment]
Both the issues should be fixed in 8c3b0f9dca95f1d0a674fc20109df926fd421620 (v1.10.1).

Unfortunately most mobile browsers stop running Javascript when in the background to save battery. Thankfully it seems that they sometimes like to run an iteration randomly every so often, which allows the manager to update and give a notification still, even if it's off by a minute or two.
